# Generated by Django 5.2.7 on 2025-11-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("body", models.TextField(verbose_name="Содержание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blogs/photo",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        choices=[
                            ("not published", "не опубликовано"),
                            ("published", "Опубликовано"),
                        ],
                        verbose_name="Опубликовано",
                    ),
                ),
                ("views_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "пост",
                "verbose_name_plural": "посты",
                "ordering": ["title"],
            },
        ),
    ]
