# Generated by Django 5.2.7 on 2025-11-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogs",
            old_name="image",
            new_name="photo",
        ),
        migrations.AlterField(
            model_name="blogs",
            name="is_published",
            field=models.BooleanField(
                choices=[("not published", "Черновик"), ("published", "Опубликовано")],
                verbose_name="Опубликовано",
            ),
        ),
    ]
