# Generated by Django 5.2.7 on 2025-11-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_rename_image_blogs_photo_alter_blogs_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="is_published",
            field=models.CharField(
                choices=[("draft", "Черновик"), ("published", "Опубликовано")],
                default="draft",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
